### ISSUE TITLE
`scripts/run_nodes.sh` fails on 12.x

### ISSUE THREAD

**Issue by oskargargas** [Cardinal-Cryptography/aleph-node#1538]
Hi,

I'm trying to setup local development chain. With minor changes to `scripts/run_nodes.sh` it works for 11.4 but fails on 12 branch. After calculating some blocks (~20) it hangs. I also see that `run_nodes.sh` was completely rewritten on `main`. Could you suggest correct configuration for 12.2?

#### System information:
```
$ uname -a
Linux ip-x-x-x-x 6.2.0-1017-aws #17~22.04.1-Ubuntu SMP Fri Nov 17 21:07:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ git status
HEAD detached at r-12.2
```

```
$ git diff
diff --git a/scripts/run_nodes.sh b/scripts/run_nodes.sh
index ca3e2047..bad03ae7 100755
--- a/scripts/run_nodes.sh
+++ b/scripts/run_nodes.sh
@@ -103,6 +103,7 @@ run_node() {
     --public-validator-addresses 127.0.0.1:${validator_port} \
     --validator-port ${validator_port} \
     --detailed-log-output \
+    --unsafe-rpc-external \
     -laleph-party=debug \
     -laleph-network=debug \
     -lnetwork-clique=debug \
```

**Comment by kostekIV** [comment]
Hi,

The script is fine but it does not have ideal user experience :) What I mean is that you have to manually remove abft backups after previous runs otherwise it will hang after 20 blocks like you have observed. For now you can add a line that does that before running the chain. This is one of the things that were improved in the script refactor you have mentioned.

For example you could add such a line, this should work but I did not check it
```bash
rm -rf "$BASE_PATH"/**/backup-stash
```
Just remember its quite hacky solution.
You could also adopt a bit of the new script to your local one, especially this section [here](https://github.com/Cardinal-Cryptography/aleph-node/blob/674f0c79fbab99d54cfeeaf3b227b977b5506948/scripts/run_nodes.sh#L297) should solve your problem.

Other solution that the old script was kinda promoting is to remove backups by hand.

**Comment by oskargargas** [comment]
Thanks @kostekIV it worked. :) Closing the issue
